graylog_addr: "192.168.1.20:12201"
http_servers:
  - port: 80
    tls: false
  - port: 443
    tls: true
  - port: 8080
    tls: true
  - port: 8000
    tls: false

port_servers:
  - port: 993 
    tls: false
    proto: "udp"
  - port: 995 
    tls: false
    proto: "udp"

  - port: 21 
    tls: false 
    proto: "tcp"
  - port: 23 
    tls: false 
    proto: "tcp"
  - port: 465 
    tls: true 
    proto: "tcp"